name: VividNetwork
main: net.vividnetwork.VividNetwork
version: 1.0
commands: 
  hreload:
   description: Reloads the hub!
  vote:
   description: gives you a link so you can vote!
  website:
   description: gives you the website link!
